server:
  port: 8080
  servlet:
    context-path: /myobject
logging:
  level:
    root: info
    com.kayak.myobject: warn
  file:
    name: logs/system.log

spring:  #数据库要预先建立好，因为hibernate只会建表不会建库
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true